[features]
seeds = false
skip-lint = false
[programs.localnet]
safe_exchange = "9Vfg3sFgXTH79HfUaQDsT4vnXTVvPhJcXcmbnd1VzYV9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/linktel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
